# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Devil Security Blog
tagline:             'Welcome to the darker side of security'
description:         ''
url:                 https://www.devilsec.io/
baseurl:             ''
paginate:            7

# About/contact
author:
  name:              True Demon
  url:               https://twitter.com/TRUExDEMON
  email:             truedemon@riseup.net

# Custom vars
version:             2.0

# Social Media
github:				https://github.com/true-demon
twitter:			https://twitter.com/TRUExDEMON


# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
